### ISSUE TITLE
Scrolling on mobile

### ISSUE THREAD

**Issue by Link2Twenty** [alex-saunders/sliding-pages#1]
At the moment you can not scroll vertically on a page when you start scrolling from within the element.

To solve this you need to use `setScrollDirection`, or at least that's what I did 🙂

> Listening for certain gestures controls the scrolling direction for touch input. For example, nodes with a listener for the track event will prevent scrolling by default. Elements can override scroll direction with this.setScrollDirection(direction, node), where direction is one of 'x', 'y', 'none', or 'all', and node defaults to this.

https://www.polymer-project.org/1.0/docs/devguide/gesture-events

**Comment by alex-saunders** [comment]
@Link2Twenty little confused what you mean by this. Are you saying if the sliding-pages element doesn't fill the whole screen, if you start scrolling within the element, it stops scrolling of the page?

**Comment by alejost848** [comment]
It seems that `setScrollDirection` is gone in 2.0. I found a possible replacement for that called `Polymer.Gestures.setTouchAction`, but using it like @Link2Twenty did in [l2t-paper-slider](https://github.com/Link2Twenty/l2t-paper-slider/blob/master/l2t-paper-slider.html#L593) still produces #2 error.
```javascript
Polymer.Gestures.addListener(this, 'track', e => this._handleTrack(e));
Polymer.Gestures.setTouchAction(this, "y");
```
Any ideas guys?
